// do not edit this file

import { Cards, TextWithTitle, TextWithPic } from "./layouts"

export enum AboutLayouts {
    cards,
    textwithtitle,
    textwithpic
}

export type AboutContentType = {
    layout: AboutLayouts,
    content: Cards | TextWithTitle | TextWithPic
}
